services:
  catalogue:
    build: ./catalogue
    image: yash8575/catalogue:1.0.0
    container_name: catalogue
    depends_on:
      - mongodb
  user:
    build: ./user
    image: yash8575/user:1.0.0
    container_name: user
    depends_on:
      - redis
  cart:
    build: ./cart
    image: yash8575/cart:1.0.0
    container_name: cart
    depends_on:
      - redis
      - catalogue
  redis:
    image: redis:7.0.5
    container_name: redis
  frontend:
    build: ./frontend
    image: yash8575/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - user
      - cart    
  
  mongodb:
    build: ./mongodb
    image: yash8575/mongodb:1.0.0  
    container_name: mongodb
  

networks:
  default:
    driver: bridge
    name: roboshop
    external: false
      