services:
  catalaouge:
    build: ./catalaouge
    image: yash8575/catalaouge:1.0.0
    container_name: catalaouge
    depends_on:
      - mongodb
  user:
    build: ./user
    image: yash8575/user:1.0.0
    container_name: user
    depends_on:
      - redis
  # cart:
  #   build: ./cart
  #   image: yash8575/cart:1.0.0
  #   container_name: cart
  #   depends_on:
  #     - redis
  #     - catalaouge
  redis:
    image: redis:7.0.5
    container_name: redis
  frontend:
    build: ./frontend
    image: yash8575/frontend:1.0.0
    container_name: frontend
    ports:
      - "80:80"
    depends_on:
      - catalaouge
      - user
      - cart    
  
  mongodb:
    build: ./mongodb
    image: yash8575/mongodb:1.0.0  
    container_name: mongodb
  

networks:
  default:
    driver: bridge
    name: roboshop
    external: false
      